### ISSUE TITLE
[events] Metadata for events

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#117]
The event timestamp should be stored as metadata, together with other app specific metadata like the originating user_id or URL.

**Comment by chriskolenko** [comment]
I would be interested in something like this. 

Currently I have some metadata coming in with every request, and i would like to use some sort of AOP pattern to access it. Rather than passing it through every command and event. 

Too much left right programming right now.

**Comment by bweston92** [comment]
We need metadata support on the command too, therefore you can have correlation IDs etc.
