### ISSUE TITLE
Contact info, mailing list, slack, irc or something?

### ISSUE THREAD

**Issue by superchalupa** [looplab/eventhorizon#118]
So far I've pulled a copy of EventHorizon and used it to make a pretty decent prototype. As far as I can tell, it's the furthest along Go library/framework for Event Sourcing/CQRS. It would be great if you listed some sort of communications channel where people could discuss.

Few questions:

What would be the best way for an HTTP POST/PUT/PATCH/etc handler to generate a command and then return the "results" of that command.

Do you have any plans on supporting NATS or NSQ for command bus or event bus?

(few others, but those are the big ones)

**Comment by superchalupa** [comment]
After being forced to sit with my thoughts for a while, what I came up with (suggestions/enhancements welcome!) is the following, using POST as the example

http post handler runs POST command with the body
aggregate command handler converts the POST to a series of events, with on of the events being a POSTRESULTS events.
The read side keeps an array of postresults events, indexed by command id
http post handler spins (tbd) until it gets the postresults and returns that to the client.

Thinking more... probably need a channel somewhere so that I can select() on it as well as my http context. Should probably store that channel in the read side and then can send the postresults event down it from the read projection event handler. Of course all of that wont work in a distributed system where read side is remote, but I don't think I need to worry about that right now, as it could probably all still be made to work.

**Comment by maxekman** [comment]
Thanks for your suggestion about another contact channel, I will consider it.

Regarding your use case I would suggest that you try to embrace DDD fully instead of trying to map normal CRUD patterns on it. Think about what you want to achieve in terms of verbs instead (add user, change address etc). What we have done is to have a sub router per aggregate (/users) with the read models mapped to GET (/users and /users/:id). That is pretty standard. On top of that we have added all commands as POSTs (/users/change_name). The POST request only returns if the command was accepted or not, any resulting events is handled be a websocket forwarder for the event bus (implemented as a very simple EventObserver).

In a few cases we wanted to wait for some expected event(s) before returning a HTTP request. That is why we added the EventWaiter in the utils folder.

I hope this clarifies how the toolkit might be used with HTTP. Granted, this would be good to add as an example to the repo. I also have an idea to add a set of HTTP adapters and tools.

**Comment by maxekman** [comment]
Also, make sure to read up on CQRS/ES in the linked resources.

**Comment by superchalupa** [comment]
I've digested a huge amount of info on CQRS/ES and believe that I've got most of the concepts down, but I'm new to it and also new to Go.

For my API, I have three completely different projects where I have to have a DMTF standard Redfish API (https://www.dmtf.org/standards/redfish). I have zero control over the REST design, I have to deal with Redfish as it is given to me and cannot design my rest API around what would work "best" for any specific solution. I would like to have a "core Redfish" implementation as it's own bounded domain that I can re-use across the different projects I'm using it on.

So far, the CQRS/ES solution has prototyped out as the most effective and straightforward solution that I've tried. I've prototyped solutions in Python and Go, with three different Go prototypes based on different REST implementations, have an existing "production" implementation in C/C++. The Go implementation based on ES has shown the most promise in being scalable and having an implementation that is straightforward and uncoupled.

In my ES prototype, I've modeled an aggregate around "Redfish Resource", modeled commands for "CreateRedfishResource", "{Add,Update,Remove}RedfishResourceProperty" as the core commands for the aggregates, and that has worked really well for the backend to create and maintain the redfish tree. So, the READ side is now pretty much hooked up and everything works well.

The next part is to then hook up the Command side to handle HTTP PUT/PATCH/POST/DELETE. This seems to be working ok, I've got an HTTP handler that formulates and sends an aggregate Command for HTTPOperation, and then the concept is that it will check that the command succeeded (return code from cmdbus.HandleCommand) and then listen for a HTTPOperationResultEvent and return that to the user. So, the current challenge is hooking up an event projector to the http handler, and it seems pretty do-able.

The "final" problem that I'll run into after I finish hooking up the command side to HTTP will be writing specific domain logic for each logical redfish entity, but I have a mental model for how that will work and will tackle that after finishing http commands.

**Comment by superchalupa** [comment]
Thanks for the pointer to EventWaiter. Looks almost exactly like what I need.

**Comment by superchalupa** [comment]
I had to run the Wait() in a goroutine and send the event back in a channel to avoid missing the event I wanted. You might consider updating the eventwaiter_test.go with something similar:

    cmdUUID := eh.NewUUID()                
    fmt.Printf("RUNNING COMMAND: %s\n", cmdUUID)                                       

    resultChan := make(chan eh.Event, 1)   

    // we have to do this wait in a gorouting so that we avoid a race condition...     
    go rh.waiter.Wait(ctx, func (event eh.Event) (bool) {                              
        if event.EventType() != domain.HTTPCmdProcessedEvent {                         
            return false                   
        }                                  
        if data, ok := event.Data().(*domain.HTTPCmdProcessedData); ok {               
            if  data.CommandID == cmdUUID {
                resultChan <- event        
                return true                
            }                              
        }                                  
        return false                       
    })                                     

    err = rh.cmdbus.HandleCommand(ctx, &domain.HandleHTTP{UUID: id, CommandID: cmdUUID, Request: r})                                                                          
    if err != nil {                                     
        return nil, err                    
    }                                      
    select {                               
    case event := <-resultChan:            
        return event.Data().(*domain.HTTPCmdProcessedData).Results, nil                              
    case <-ctx.Done():                     
        // the requestor cancelled the http request to us. We can abandon              
        // returning results, but command will still be processed                      
        return "COMMAND TIMEOUT", nil      
    }

**Comment by superchalupa** [comment]
Crap, I guess that could still race unless I signal ready?

**Comment by superchalupa** [comment]
Looks like the only way to fix Wait() not race with a command submission is to split it into SetupWait() (eh.UUID), and an actual Wait(eh.UUID).


Here is what I came up with and it looks like it works ok. What do you think?

type singleWaiter struct {                 
    ch chan eh.Event                       
    match  func(eh.Event)(bool)            
}                                          

// EventWaiter waits for certain events to match a criteria.                           
type EventWaiter struct {                  
    waits   map[eh.UUID]singleWaiter       
    waitsMu sync.RWMutex                   
}                                          

// NewEventWaiter returns a new EventWaiter.                                           
func NewEventWaiter() *EventWaiter {       
    return &EventWaiter{
        waits: map[eh.UUID]singleWaiter{}, 
    }                                      
}                                          

// Notify implements the eventhorizon.EventObserver.Notify method which forwards       
// events to the waiters so that they can match the events.                            
func (w *EventWaiter) Notify(ctx context.Context, event eh.Event) error {              
    w.waitsMu.RLock()                      
    defer w.waitsMu.RUnlock()              
    for _, sw := range w.waits {           
        if sw.match(event) {               
            sw.ch <- event                 
        }                                  
    }                                      
    return nil                             
}                                          

// SetupWait sets up the waiter with the match function                                
// The match function can be used to filter or otherwise select
// interesting events by analysing the event data.                                     
func (w *EventWaiter) SetupWait(match func(eh.Event) bool) (id eh.UUID, ch chan eh.Event) {                                                                                   
    id = eh.NewUUID()

    ch = make(chan eh.Event, 1) // Use bufferd chan to not block other waits.
    sw := singleWaiter{ch: ch, match: match}

    // Add us to the in-flight waits and make sure we get removed when done.           
    w.waitsMu.Lock()                       
    w.waits[id] = sw                       
    w.waitsMu.Unlock()                     

    return 
}                                          

func (w *EventWaiter) CancelWait(id eh.UUID) {                                         
    w.waitsMu.Lock()
    delete(w.waits, id) 
    w.waitsMu.Unlock()
}

**Comment by superchalupa** [comment]
The way I used the above in my http handler was:

id, ch := SetupWait()
defer CancelWait(id)
HandleCommand(...)

select{
case event := <-ch:
             ...
case <-ctx.Done:
             ...
}

**Comment by superchalupa** [comment]
I created this commit: https://github.com/superchalupa/eventhorizon/commit/9326c8d34d4e5938572c946cd1047197abe2fa22

It passes the existing test cases without change. I provide SetupWait and CancelWait functions, and then re-implemented Wait() in terms of the helpers. In my code, I just use the helpers directly.

I don't know how to setup github to create a pull request with just this commit id without merging the entire branch. (There are two commits in my repo: 1) changes all references from github.com/looplab/eventhorizon to github.com/superchalupa/eventhorizon, and 2) this commit.) Obviously, you don't want that first commit. Cherry pick, maybe?

**Comment by superchalupa** [comment]
Ok, figured out the correct incantation to separate this commit out.

**Comment by maxekman** [comment]
I'll take a look at the PR.

In the meantime if you don't want to rewrite all the paths I really recommend a vendoring tool such as Glide, which knows how to pull your version of Event Horizon but under the original name.

**Comment by superchalupa** [comment]
Thanks for the tip. I've been meaning to investigate glide, just hadn't had the chance. Looks like it works out ok once I've figured out a couple fiddly things.

**Comment by maxekman** [comment]
Fixed in #137.

**Comment by maxekman** [comment]
Opened #138 to track the issue with your suggestion for project communication.
