### ISSUE TITLE
Need ability to snapshot aggregates (squash event history)

### ISSUE THREAD

**Issue by superchalupa** [looplab/eventhorizon#120]
I am running on an embedded system with limited RAM and flash storage. I need a way to snapshot all of my aggregates, basically squashing history.

The way I thought I might be able to do it is to traverse through all of my aggregates and send them each, in turn, a SnapshotCommand. Then, instead of StoreEvent(), the aggregate could call StoreSnapshot( Event{} ). My aggregates can be encapsulated in a CreateFoo event, so that would serve well to snapshot the aggregate.

Is there a better way to do this? Any thoughts on where to begin implementing something like this?

**Comment by maxekman** [comment]
Thanks for the feedback. Let's discuss further in the original issue #33.

**Comment by superchalupa** [comment]
It wasn't clear to me that issue #33 was related to being able to truncate event history? Is it ok to update that issue with this info?
