### ISSUE TITLE
Move asynchronous event handling into a middleware

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#126]
This would make the interfaces cleaner and allow for cleaner configuration of the behavior of event handling.

**Comment by grrtrr** [comment]
I have been thinking about goroutine-safety and was thinking about wrapping things that may need to run in parallel into their own Actors (actor model, as in Akka).
This would allow both goroutine safety (usability in concurrent context), as well as keep the state internal. Would this help with your intended design?

**Comment by maxekman** [comment]
Sounds interesting, could you point to an article or reference implementation describing it?

**Comment by grrtrr** [comment]
Bryan Boreham of weaveworks presented [An Actor Model in Go](https://www.slideshare.net/weaveworks/an-actor-model-in-go-65174438) at the UK conference.

I have successfully used this pattern in projects and sample code; ping me when you are back.

**Comment by joeblew99** [comment]
i would look into using this actor implementation: https://github.com/AsynkronIT/protoactor-go

There is also a corresponding c# implementation. c# and golang can communicate this way. Not that this project needs that, but i have used its RemoteService for interop between Xam c# and golang. I have also used with on mobiles for running services that must not die.

Anyway, this provides the needed supervision of actors and restart ability wanted.
Roger (who is the mainter of Protoactor) would be definitely interested is using CQRS/ES with Protoactor...

**Comment by grrtrr** [comment]
@joeblew99 I wished I had known of this implementation before doing implementation work. Will definitively give it a look, thank you.
@maxekman Not knowing other implementations meant I am swamped with work, sorry for not getting back.

**Comment by joeblew99** [comment]
Well thats life, and i am not expert at CQRS and actors.

From what i have read often the actors use the CQRS system under them. Its a well used pattern it seems, instead of using Process Managers.
Am curious what others think too...

The Actor code has some simplified event based system.

https://github.com/AsynkronIT/protoactor-go/tree/dev/eventstream

https://github.com/AsynkronIT/protoactor-go/blob/dev/actor/mailbox.go
https://github.com/AsynkronIT/protoactor-go/tree/dev/mailbox

**Comment by maxekman** [comment]
I must definitely learn more about this also, thanks for all the resources so far!

**Comment by maxekman** [comment]
The Protoactor lib looks really cool! Feels familiar as I did some Erlang a really long time ago.

**Comment by maxekman** [comment]
Maybe having some kind of bridge to the event bus could be useful in some cases.

**Comment by grrtrr** [comment]
You are right - Erlang had these things figured out long before Akka came along. As the framework shows, it is not too hard to translate these concepts into go.

Also agree with the bridge concept -- it is essentially how I got things moving with a 'concurrent bus'.
I am hoping to open source these ideas within the next 3..4 weeks.

**Comment by maxekman** [comment]
Nice! Looking forward to it.

Related to this I read this interesting article, it talks about some (well known) drawbacks of how concurrency work in Go: https://medium.com/@sargun/go-concurrency-considered-harmful-26499a422830

**Comment by grrtrr** [comment]
@maxekman - Agree, obviously Erlang is a better language. Go has a lot of other advantages, such as productivity and ease of use.

I have assembled the concurrent command/event bus [here](https://github.com/grrtrr/magicbus). 

Each Aggregate has its own actor, the bus itself is also an actor, which means that commands/events are fully decoupled. Each Aggregate gets commands/events in _serialized fashion_, i.e. _one at a time_. As a result, the Aggregate code can be completely sequential, no need for locking.

Aggregate IDs are cluster wide and use node IDs (IP addresses). One bus can be connected with a remote one, this is sketched in remote.go.

Any comments, questions, ideas are welcome.
