### ISSUE TITLE
projector: could not save model: Wrong type for 'u'. Expected a object

### ISSUE THREAD

**Issue by chriskolenko** [looplab/eventhorizon#145]
When returning a nil from a projector I'm getting an error:
projector: could not save model: Wrong type for 'u'. Expected a object

The code reads like it should remove the model. Am I doing something wrong with configuring the event type?

**Comment by maxekman** [comment]
Can you provide a bit more detail about the model you are trying to save and the event?

**Comment by chriskolenko** [comment]
It's not a complex model. 

CreateTeamCommand with a Title
TeamCreated Save to read model

Saga that listens for TeamCreated
If a Team with the same name exists Return DenyTeamCommand

DenyTeam sets a bool in the aggregate root and raises TeamDeniedEvent
Projector sets the model to nil

**Comment by maxekman** [comment]
It looks like it ends up trying to save the model, that is the only way to get that error: https://github.com/looplab/eventhorizon/blob/master/repo/mongodb/repo.go#L185

Are you sure you are returning `nil` from the `Project()` method of your projector?

**Comment by maxekman** [comment]
Further about the actual error, do you have types unsupported my mgo in your model? I recognize that error and if I remember correctly it had to do with unsupported types.

**Comment by chriskolenko** [comment]
Fixed my issue:
```
if !ok {
  return nil, errors.New("model is of incorrect type")
}

// Apply the changes for the event.
switch event.EventType() {
case types.TeamDeniedEvent:
  i = nil // <- this was causing the issue. Returning nil, nil here worked. 
case types.TeamCreatedEvent:
  .....
}

return i, nil
```

**Comment by maxekman** [comment]
Ah, interesting. The confusing `nil != nil` thing.
