### ISSUE TITLE
[project] Move DB/messaging implementations to separate repos

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#147]
Name external reps with an eh prefix: `eh-mongodb`, `eh-redis`.

Also add a list in the readme with links to the implementations.

**Comment by joeblew99** [comment]
This change will allow other DB implementations to be build as "plugins" ?? 
Asking because i need different store types. BoltDB, raft, Pilosa

**Comment by maxekman** [comment]
Exactly! I would like to be able to support different implementation without maintaining them all in the main repo.

**Comment by joeblew99** [comment]
big +1 from me :)

I intend to build the following plugins:
- BoltDB with Storm ( https://github.com/asdine/storm ) for a KV based DB.

- Bleve ( https://gitter.im/blevesearch/bleve ) for un structured text search.

- Pilosa ( https://github.com/pilosa/pilosa ) for structure search. 

With boltDB you loose allow of the search capability you have with a full DB, but instead you can then use Bleve and Pilosa to get them back. 

How best to combine them with a CQRS architecture is debatable i feel. I see two options:
1. You combine them into a Service called "store" (for example) with a wrapper API giving you storage and search
2. You make them separate Services as Infrastructure and then use them as needed. 

Let me knwo your thoughts...

**Comment by maxekman** [comment]
Sounds cool! I'm not familiar enough with the DBs to make any suggestions apart from guesses but either of your solutions could work. The first trades coupling for usability which could be good or bad depending on your POV. Separate storages (and used by different projectors in client code) for the different DBs would probably be a cleaner implementation.

Feel free to open issues for the different implementations to keep us informed about the progress and to maybe add the links to your repo when finished.

**Comment by joeblew99** [comment]
will do...

Did you see the stuff about actors with cqrs  in the other issue. I am using both.

**Comment by maxekman** [comment]
I have changed my mind on this and will continue to have a few core adapters in the project. Both for usability and easy reference for other implementations.
