### ISSUE TITLE
checkCommand returns missing field for boolean fields which is set to false

### ISSUE THREAD

**Issue by nilpath** [looplab/eventhorizon#16]
Hi I ran into a problem when trying to create a Todo API using your framework.

I'm trying to send the following command

```
type UpdateTodo struct {
	TodoID string
	Name   string
	Done   bool
}

id := eventhorizon.NewUUID()
cmd := UpdateTodo{TodoID: id, Name: "Todo 1", Done: false}
```

but in doing so it seems to complain about the field Done is missing and I think it is [checkCommand](https://github.com/looplab/eventhorizon/blob/80015c4c9ca1b4d337f934c4cc94f755a9e41108/commandhandler.go#L129) method that is creating this problem for me.

here is demo of the issue as well https://play.golang.org/p/IRzcOGIAgS

Are you recommending sending boolean values in another way? this problmen probably holds true for integers as well. pretty much any default values.

**Comment by nilpath** [comment]
@maxekman ran it through my use case and it seems like it solves my problem :) 

I think it is a hard problem with golang, trying to differentiate between what is set by the program and what is an uninitialised value. I haven't really found a good way to do it, unless you pointers.

**Comment by maxekman** [comment]
Thanks, I'll merge it then.
