### ISSUE TITLE
[commandhandler] Add middleware interface and utilities

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#161]
Should work similarly to the common `func(http.Handler) http.Handler` pattern, including some kind of application function.

Some inspiration: https://medium.com/@matryer/writing-middleware-in-golang-and-how-go-makes-it-so-much-fun-4375c1246e81

**Comment by bweston92** [comment]
You will want to know of any errors so you can report them so something like:

```
type MiddlewareHandler func(cmd *Command, next func()) error

func CommandHandlerObserver(cmd *Command, next func()) error {
  commandsDispatched.Inc()
  err := next(cmd)

  if err != nil {
    commandsErrored.Inc()
    fmt.Printf("error executing %s on %s[%s]: %s\n", cmd.CommandType(), cmd.AggregateType(), cmd.AggregateID(), err)
  } else {
    fmt.Printf("executed %s on %s[%s]\n", cmd.CommandType(), cmd.AggregateType(), cmd.AggregateID())
  }

  return err
}

```

**Comment by maxekman** [comment]
Not sure what you mean, you will get that with an interface like I described. Remember that the command handler already returns an error, compared to the http.Handler.
