### ISSUE TITLE
[doc] Create an example of a Saga for multiple aggregates

### ISSUE THREAD

**Issue by giautm** [looplab/eventhorizon#184]
Hi. I want to see an example of multiple aggregates in a project to see how they communicate. :)

**Comment by maxekman** [comment]
Sounds like it could be a good example. Could you describe in more detail what you would like to highlight?

**Comment by giautm** [comment]
I want to see:
- How two aggregate roots can communicate together.
- How to can use two aggregates in a domain service which require two aggregates to complete a command.

**Comment by maxekman** [comment]
Basically you should never have a command that directly affects multiple aggregate roots. If you need that you should probably create a saga that issues one of the commands as a side effect to an event from the first command.

Relating to your question, a more complex saga example could be good to have. I'll try to add that at some point.

**Comment by giautm** [comment]
Tks, I will waiting for the example. May I contribute to that PR for learning.

**Comment by giautm** [comment]
@maxekman : Hi, Can I Direct Message to you?

**Comment by maxekman** [comment]
You can propose an example if you want to learn about it. 

Maybe a e-commerce checkout could be a good example:
- One simple domain called `Order`, with commands and events for `Create`, `Fulfil` and `Reject`.
- One simple domain called `Payment`, with a command `Request` with events `Accepted` and `Denied`.
- A saga that reacts on `Order.Created` and issues a `Payment.Request` command. It will then fulfil or reject the order depending on if the payment was accepted or denied.

**Comment by chaudharisuresh997** [comment]
Idea is too have aggregate.
One aggregate does not have other aggregate instead it can have id of aggrgate.
If u read akka actor model it says result of one aggrgate can be passed to other.
Here one aggrgate result can be passed to other.

**Comment by screwyprof** [comment]
Shouldn't a saga be able to react on a bunch of events? Currently It's interface only relies on a single event only.

**Comment by maxekman** [comment]
In that case the saga has to keep track of incoming events until it has collected all affected events. Then it can continue processing. A saga is meant to keep its own internal state if required.
