### ISSUE TITLE
[aggregatestore/model] Should support sending events

### ISSUE THREAD

**Issue by superchalupa** [looplab/eventhorizon#185]
model based aggregate store should have the same api to send events out on save as the event based aggregate store. This would close a race condition because currently save() method may not have run yet if you use a closure-based event send from a model. My example was a CreateObject command sending out some ObjectUpdated events, the ObjectUpdated events were being seen before the ObjectCreated event, causing a big problem.

**Comment by bweston92** [comment]
@superchalupa can you submit a test case showing this failing? Just so I can understand what you mean.

**Comment by superchalupa** [comment]
Ok, let me see if I can explain it... not sure exactly how to submit a test case for this.

Here: https://github.com/looplab/eventhorizon/blob/master/examples/guestlist/domain/aggregate.go

You import this:
	"github.com/looplab/eventhorizon/aggregatestore/events"

Which lets you compose your InvitationAggregate with an AggregateBase, like this:

type InvitationAggregate struct {
	// AggregateBase implements most of the eventhorizon.Aggregate interface.
	*events.AggregateBase

which lets you do this:

type InvitationAggregate struct {
	// AggregateBase implements most of the eventhorizon.Aggregate interface.
	*events.AggregateBase

But there is no such AggregateBase in eventstore/model, unless I'm completely missing something.

**Comment by superchalupa** [comment]
What I would like to have is a similar AggregateBase interface in the aggregatestore/model with a similar "StoreEvent" API.

The issue is that HandleCommand() currently instantiates my object, and if my object emits events, the event can be processed before the aggregate has been stored in the database, and there is no way for me to resolve that race condition.

**Comment by maxekman** [comment]
Sounds good to me. I propose a `EmitEvent` method on the model aggregate store, which is optional to use in cases like yours. What do you think?

**Comment by superchalupa** [comment]
I think that would be a fine solution to this problem. Thank you.

**Comment by superchalupa** [comment]
Thanks, this looks great! I'll update my stuff and test out.

**Comment by maxekman** [comment]
Perfect, file an issue if something doesn't work as expected. I have not yet tried this out apart from the tests!
