### ISSUE TITLE
[mongodb] Use maintained driver

### ISSUE THREAD

**Issue by bweston92** [looplab/eventhorizon#190]
Current MongoDB driver has been deprecated a while, whilst there is some forks which are maintained not everyone uses the same.

However I have just seen that MongoDB now have an official driver: https://github.com/mongodb/mongo-go-driver

Thoughts?

**Comment by maxekman** [comment]
Thanks! I hadn't noticed they had an official driver. I will look into using that instead. Will also move the MongoDB implementation out from this main repo soon, see #147.

**Comment by maxekman** [comment]
I think the globalsign/mgo driver will be the first step, as it requires minimal changes: https://github.com/globalsign/mgo

**Comment by bweston92** [comment]
Well if you do it when you split out then I don’t see the point in going
with unmaintained packages when people have to change anyway.

**Comment by maxekman** [comment]
And as I said, it’s just a first step, mostly to get some of the performance benefits from the updated version.
