### ISSUE TITLE
[mongodb] Set default namespace

### ISSUE THREAD

**Issue by badoet** [looplab/eventhorizon#203]
currently we added a custom namespace for our mongodb store
but this come at the cost of needing to add `ctx = eh.NewContextWithNamespace(ctx, s.config.MongoDB.Namespace)` in every handler function
is there a place where i can set this context with the MongoDB namespace globally at startup?
the implication for forgetting to add that piece of code is the store will go to `default` namespace in mongodb and it is a big pain to fix

**Comment by maxekman** [comment]
Fixed in #260.
