### ISSUE TITLE
[repo/memory] Possible data races due to shallow copy

### ISSUE THREAD

**Issue by superchalupa** [looplab/eventhorizon#207]
Items are handled as shallow copies in the memory entity store, which could possibly lead to data races. Could be fixed by deep copying the entities, marshalling/unmarshalling or using some other more advanced in memory store than a map/slice.

Originally found when using the Model Aggregate Store:

Data race found in the new model event publisher code, need some locking.

The situation is as follows:
  1) I execute a command to create a resource
  2) creation of the resource emits a "resource created" event
  3) some saga listens for that event and executes an UpdateResource command
  4) resource update command emits a "resource updated" event
  5) data race exists in between the EventsToPublish() call from the second command and ClearEvents() called from the first command.

==================
WARNING: DATA RACE
Read at 0x00c420240090 by main goroutine:
  github.com/superchalupa/go-redfish/src/redfishresource.(*RedfishResourceAggregate).EventsToPublish()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/aggregatestore/model/eventpublisher.go:41
 +0x4f
  github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/aggregatestore/model.(*AggregateStore).Save()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/aggregatestore/model/aggregatestore.go:78
 +0x196
  github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/commandhandler/aggregate.(*CommandHandler).HandleCommand()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/commandhandler/aggregate/commandhandler.g
o:73 +0x240
  main.(*MyLogger).makeLoggingCmdHandler.func1()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/cmd/ocp-server/logging.go:80 +0x191
  github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon.CommandHandlerFunc.HandleCommand()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/commandhandler.go:31 +0x5f
  github.com/superchalupa/go-redfish/src/ocp/session.(*Service).AddResource()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/src/ocp/session/sessions.go:173 +0x1e25
  github.com/superchalupa/go-redfish/src/obmc.InitOCP()
 .... elided

Previous write at 0x00c420240090 by goroutine 13:
  github.com/superchalupa/go-redfish/src/redfishresource.(*RedfishResourceAggregate).ClearEvents()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/aggregatestore/model/eventpublisher.go:46
 +0x4f
  github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/aggregatestore/model.(*AggregateStore).Save()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/aggregatestore/model/aggregatestore.go:79
 +0x1be
  github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/commandhandler/aggregate.(*CommandHandler).HandleCommand()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/commandhandler/aggregate/commandhandler.g
o:73 +0x240
  main.(*MyLogger).makeLoggingCmdHandler.func1()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/cmd/ocp-server/logging.go:80 +0x191
  github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon.CommandHandlerFunc.HandleCommand()
      /home/michael_e_brown/go/src/github.com/superchalupa/go-redfish/vendor/github.com/looplab/eventhorizon/commandhandler.go:31 +0x5f
DBUG[04-03|19:48:58] Executed Command                         CMD="&{ID:5c11db31-2fe9-4186-96c7-8cec95dcdfc1 ResourceURI:/redfish/v1/Chassis Type:#Cha
ssisCollection.ChassisCollection Context:/redfish/v1/$metadata#ChassisCollection.ChassisCollection Privileges:map[GET:[Login] POST:[] PUT:[] PATCH:[]
DELETE:[]] Plugin: Properties:map[Name:Chassis Collection] Meta:map[] Private:map[] Collection:true}"
  github.com/superchalupa/go-redfish/src/stdcollections.NewService()

**Comment by maxekman** [comment]
What entity store are you using?

**Comment by superchalupa** [comment]
I'm using the memory entity store. I fixed this in my tree by providing my own implementation of the interface:

```
// PublishEvent registers an event to be published after the aggregate
// has been successfully saved.
func (a *RedfishResourceAggregate) PublishEvent(e eh.Event) {
	a.eventsMu.Lock()
	defer a.eventsMu.Unlock()
	a.events = append(a.events, e)
}

// EventsToPublish implements the EventsToPublish method of the EventPublisher interface.
func (a *RedfishResourceAggregate) EventsToPublish() []eh.Event {
	a.eventsMu.RLock()
	defer a.eventsMu.RUnlock()
	retArr := make([]eh.Event, len(a.events))
	copy(retArr, a.events)
	return retArr
}

// ClearEvents implements the ClearEvents method of the EventPublisher interface.
func (a *RedfishResourceAggregate) ClearEvents() {
	a.eventsMu.Lock()
	defer a.eventsMu.Unlock()
	a.events = []eh.Event{}
}
```

https://github.com/superchalupa/go-redfish/blob/master/src/redfishresource/aggregate.go: lines 103+

**Comment by superchalupa** [comment]
And my aggregate has:

```
	events   []eh.Event
	eventsMu sync.RWMutex
```

which goes along with the code above.

**Comment by maxekman** [comment]
Ok, this is an issue with the memory event store. It does not create new items on load, which it really should to mimic a production system with a DB. I'm changing the issue to be about that instead.
