### ISSUE TITLE
Rebuild model from events

### ISSUE THREAD

**Issue by jacklam718** [looplab/eventhorizon#208]
How do I replay all events and rebuild the read model from scratch?

**Comment by maxekman** [comment]
Currently you have to manually wire up the components to do that. It is possible that this will be added in the future.

**Comment by maxekman** [comment]
Unfortunately I don't have an example ready to show.

**Comment by jacklam718** [comment]
Thanks! Wish I can see the example soon. i spend a lot of time thinking about that and search relevant resources still don't know how.

**Comment by rodrigosillos** [comment]
Hello Jack! I would like to talk about your project: https://github.com/jacklam718/myDesktop
You are avaiable?
Thank you!

**Comment by rodrigosillos** [comment]
Hello @jacklam718 !
I would like to talk about your project: https://github.com/jacklam718/myDesktop
You are avaiable?
Thank you!
