### ISSUE TITLE
[mongodb] UUID in repo should be encoded as string

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#249]
https://github.com/looplab/eventhorizon/blob/master/repo/mongodb/repo.go#L245

Should be done as here: https://github.com/looplab/eventhorizon/blob/master/eventstore/mongodb/eventstore.go#L148

**Comment by apterf** [comment]
Hi @maxekman , checking the interfaces and existing implementation in `eventstore`.

The ID in data struct is storing as a `string` and interface function will return a parsed UUID.
UUID will still be the single format for connecting all eventhorizon interfaces.

Tried to test it with:
Step 1. Read model ID stored as string (to keep the model as simply layer)
Step 2. Upsert with ID as string
Steo 3. Update test cases

Tried with this approach, you may take a look first:
https://github.com/apterf/eventhorizon/commits/Store-ID-as-string-in-read-model

Alternate methode:
Step 1. Use UUID as ID type in read model
Step 2. Perform a partial update in `repo` to save models

Not sure which one or any other one do you prefer.

**Comment by maxekman** [comment]
Thanks for the input. I’ll take a closer look at this soon when back at work.
