### ISSUE TITLE
How to handle publish event failures in aggregatestore.Save

### ISSUE THREAD

**Issue by mortyccp** [looplab/eventhorizon#251]
https://github.com/looplab/eventhorizon/blob/6fd1f17be266c5a217ff8c05dd1403d722cae7f2/aggregatestore/events/aggregatestore.go#L142-L157

If the eventstore saves the events but the eventbus fails to publish the events.
How should we handle this situation?

**Comment by maxekman** [comment]
This currently has to be provided as a guarantee of the event bus. It could definitely be improved. Sorry for the late reply!

**Comment by mortyccp** [comment]
Okay. EventBus should never failed. 🤣
