### ISSUE TITLE
How does one correctly pass a context to the commandbus?

### ISSUE THREAD

**Issue by LennyPenny** [looplab/eventhorizon#259]
Hey, 
currently we are passing down the context of an incoming http request down into the commandbus. 
This seems to make saving projections to mongodb fail, as they are saved at some later time, when the request context is already cancelled. 

What is the canonical way to fix this issue? We need the context to pass logging meta information. 
Should one just copy the context metadata into a new context that does not get cancelled? That seems a bit dirty though

Has anyone else dealt with this problem?

**Comment by maxekman** [comment]
Yes, creating a new context for the command handling is usually what I do, which would contain the required metadata for further processing.
