### ISSUE TITLE
A link in the README is dead

### ISSUE THREAD

**Issue by gust1n** [looplab/eventhorizon#274]
**Describe the bug**
The link in the README, https://codebetter.com/gregyoung/2010/02/16/cqrs-task-based-uis-event-sourcing-agh/ seems dead.

**To Reproduce**
1. Go to the README
2. Click on the link (https://codebetter.com/gregyoung/2010/02/16/cqrs-task-based-uis-event-sourcing-agh/)
3. See error

**Comment by maxekman** [comment]
It actually works as linked in the readme (with HTTP), but it doesn't work with HTTPS (as in your issue description). Must have been your browser that auto-redirected to HTTPS.
