### ISSUE TITLE
EventStore: support Load events with aggregateType

### ISSUE THREAD

**Issue by giautm** [looplab/eventhorizon#313]
**Is your feature request related to a problem? Please describe.**

The current interface of EventStore doesn't have `aggregateType` in the Load receiver. So, when I trying to support multiple aggregates with the same ID, currently it's impossible. 

https://github.com/looplab/eventhorizon/blob/ff90e644d29d016358150c619ec279cc3077e922/eventstore.go#L24-L31

But, the aggregate score really has `aggregateType` in Load, so I think we just simply modify the EventStore interface then add `aggregateType`.

https://github.com/looplab/eventhorizon/blob/ff90e644d29d016358150c619ec279cc3077e922/aggregatestore/events/aggregatestore.go#L78-L95

**Describe the solution you'd like**

Change the EventStore interface to:
```go
// EventStore is an interface for an event sourcing event store.
type EventStore interface {
	// Save appends all events in the event stream to the store.
	Save(ctx context.Context, events []Event, originalVersion int) error

	// Load loads all events for the aggregate id and type from the store.
	Load(ctx context.Context, id uuid.UUID, aggregateType AggregateType) ([]Event, error)
}
```

Another Interface should add, this interface helpful when you trying to implement the snapshot feature. Load events from a specified version then apply them to the current state.
```go
// EventStoreVersion is an interface for an event sourcing event store.
type EventStoreVersion interface {
	EventStore
	// LoadFromVersion loads all events for the aggregate id and type from the store.
	LoadFromVersion(ctx context.Context, id uuid.UUID, aggregateType AggregateType, fromVersion int) ([]Event, error)
}
```

so, the EventStore#Load implement, it just call to LoadFromVersion with `fromVersion=1`.
```go
// Load implements the Load method of the eventhorizon.EventStore interface.
func (s *EventStore) Load(ctx context.Context, id uuid.UUID, aggregate eh.AggregateType) ([]eh.Event, error) {
	return s.LoadFromVersion(ctx, id, aggregate, 1)
}

// LoadFromVersion implements load events from storage 
func (s *EventStore) LoadFromVersion(ctx context.Context, id uuid.UUID, aggregate eh.AggregateType, fromVersion int) ([]eh.Event, error) {
	// ...
}
```

**Comment by giautm** [comment]
For reference, I have done the same things for my fork: https://github.com/tikivn/eventhorizon/pull/5/files

**Comment by maxekman** [comment]
Load from version is definitely something that should be addad.

But I don't fully understand when you would have the same ID for multiple aggregates?

**Comment by giautm** [comment]
> But I don't fully understand when you would have the same ID for multiple aggregates?

To divice a big aggregate into mutiple aggregates. Every aggregate share an same ID so I can fire command directly on the Event Handler. The only blocker currently is EventStore#Load.

**Comment by maxekman** [comment]
Hm, it sounds like your domain is maybe not fully developed. A big aggregate is fine, and can even be composed of sub-aggregates, but there should only be one aggregate root that has the ID for the lookup. Can you please provide a short code example if possible? I would really like to understand the use case before considering this change.

**Comment by giautm** [comment]
> your domain is maybe not fully developed
I'm not sure.

As I can remember, I had two aggregates named: `RequestAggregate` and `ManagementAggregate`.
- `RequestAggregate` was designed to handle all information about a delivery request: Pickup/DropOff address, items detail, ...
- `ManagementAggregate` was designed to handle all information about the boxes in that request, it created after the Request has been approved. It also contacts information about the delivery status.

So, If I have 2 two IDs differently, I have to save them to somewhere then lookup alter to fire two commands for two aggregates. (ex: Cancel both of them).

PS: I don't have access to that code anymore.

**Comment by maxekman** [comment]
Sounds like a flaw in the modelling. These aggregates should probably not share the ID.

A follow up question; do you really need this feature if you don't have access (or work on?) the original source code?

**Comment by giautm** [comment]
> do you really need this feature if you don't have access to (or work on?) the original source code?

Yes, because I don't think we should not share the ID. Entity's ID is something meaningful in the real world. For example, Netflix uses `S1:E1` as an ID for view tracking. The same ID can be also used for Episode information. Use a random ID (UUID) for the entity may be a mistake.

**Comment by maxekman** [comment]
I still think the modelling is flawed. You probably want to use multiple projections/views to access your data. There should still be only one aggregate root responsible for coordinating the related events. See here for more info: https://stackoverflow.com/questions/49985156/aggregates-in-event-sourcing-pattern

**Comment by maxekman** [comment]
Will close this until there is stronger evidence that this is needed.
