### ISSUE TITLE
[Question] Multiple domains

### ISSUE THREAD

**Issue by LiorF-BDBQ** [looplab/eventhorizon#318]
Hi,

We're looking at using EventHorizon for an app that would require the creation of multiple domains.

Regarding modeling in such a scenario - Assuming I have a "Product" and each Product can be referenced to multiple "Attributes" aggregate. Assuming I persist a new attribute, what's the correct way to trigger the "Product" once an attribute related to it changed?

Is there way to dispatch/listen to events after projection to the read repo? I.e. chaining EventHandlers in a specific sequence.
For instance - I would like to log after a successful write to the read repo.

**Comment by maxekman** [comment]
There is currently no way to listen to when a projection has actually happened. This can be seen as a drawback, but at the same time I would be VERY careful of using the read models in any business logic.

I can see two alternatives:

1. Use a saga that listens to the domain events for Products and Attributes and sends appropriate commands to sync whatever state needs to be synced, totally ignoring the read models.
2. Make the Attribute into a value object on the Product. The fewer aggregate (roots) you have the fewer synchronisation issue there will be.

When the outbox pattern eventually gets implemented (for other reasons; atomicity etc) it might be possible to get notified when projections are done.

Hope this helps!

**Comment by LiorF-BDBQ** [comment]
Thanks!
