### ISSUE TITLE
More explicit error message when trying to project event to deleted projection

### ISSUE THREAD

**Issue by klowdo** [looplab/eventhorizon#362]
**Describe the bug**
When a event is projected on a deleted projection it returns "the incorrect projected entity version" 
this is mainly for development experience since you should always check for exists in aggregate 

**To Reproduce**
1. Create an aggregate item and a saga that triggers on that created event and later send back `UpdateCommand` to aggreate async creating  `UpdateEvent` 
2. Send delete command against aggregate
3. the aggregate projection should apply events `CreatedEvent`, `DeletedEvent`, `UpdateEvent`
4. See error "the incorrect projected entity version"  in projector

**Expected behavior**
same as **To Reproduce** 1-3
but step 4 should produce "projected entity is deleted"

**Possible soultion**
if the event version that is about be projected is more than one and projection entity version is zero then the entity is deleted

**Comment by maxekman** [comment]
Good suggestion! The only issue I can see is that if the irregular versioning option is used it's hard to know which is in fact the first event which should be projected.
