### ISSUE TITLE
Slack channel sign-up link in the README.md is no longer active

### ISSUE THREAD

**Issue by zdraganov** [looplab/eventhorizon#375]

**Comment by JohnRoesler** [comment]
I ran into the same issue - I found the channel in gopher slack: https://gophers.slack.com/archives/C6ML5J12M

**Comment by maxekman** [comment]
Great observations! Can one of you make a PR with an updated link? That would be great! Thanks

**Comment by zdraganov** [comment]
@maxekman done.
