### ISSUE TITLE
Is it going to be maintained?

### ISSUE THREAD

**Issue by murbanowicz** [looplab/eventhorizon#393]
Hi,
this is a great library, but it looks like maintainers lost interest in it.
Is it going to be maintained at all?

**Comment by maxekman** [comment]
Yes, I'm maintaining it, but not much new development from me personally. I'm happy to accept PRs with fixes and features. Some of my previous customers (when I was consulting, now I'm employed) use this in production systems, and I have given them maintenance rights if they need it too.
