### ISSUE TITLE
[eventbus] Google Cloud Pub/Sub

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#67]
An implementation of the EventBus interface that uses the cloud.google.com/go/pubsub package.

**Comment by grillbiff** [comment]
Just a heads up that Google Pubsub does not guarantee in which order published messages arrive to the subscribers. We dropped our Google Pubsub integration after realizing this. Also noticed that there is already a Publisher implementation of Google Pubsub for EH

https://cloud.google.com/pubsub/docs/ordering
```
Google Cloud Pub/Sub provides a highly-available, scalable message delivery service. 
The tradeoff for having these properties is that the order in which messages are received by subscribers is not guaranteed. 
While the lack of ordering may sound burdensome, there are very few use cases that actually require strict ordering.
```

**Comment by maxekman** [comment]
Yes, that is mostly why this issue is still open. The work that is done on the GCP PubSub event bus is not complete. It lacks the message ordering as you noted, and possibly other production related tweaks.

**Comment by maxekman** [comment]
I should have documented the implementation process better by adding that info here before.
