### ISSUE TITLE
[eventstore] Google Cloud Datastore

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#68]
An implementation of the EventStore interface using the cloud.google.com/go/datastore package.

**Comment by ivanjaros** [comment]
Datastore is VERY slow, I would not recommend it for anything more than a backup. And even then I would recommend storing events as files in GC Store(aka S3) instead.

**Comment by maxekman** [comment]
Thanks for the input, I'll try to do some measurements.

**Comment by maxekman** [comment]
Will not be implemented.
