### ISSUE TITLE
[commandbus] Add formal mechanism for validating commands

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#71]
For example a validation method on the aggregate interface, or a middleware that runs before handling the command in the aggregate.

**Comment by maxekman** [comment]
A flexible way to do it would be to create a separate command handler middleware that does only validation.

**Comment by apterf** [comment]
Hi Max,

It will be great to have this implemented and hope to help with it.

As you suggested, I'm planning to add a middleware `validator` 
as `middleware/commandhandler/validator/commandhandler.go`.

1. Add a command interface with method `Validate()`
```go
type Command interface {
	eh.Command

	// Validate returns the error when validating the command.
	Validate() error
}
```

2. The middleware will simply call the validation, if failed, return with the error
```go
func NewMiddleware() eh.CommandHandlerMiddleware {
	return eh.CommandHandlerMiddleware(func(h eh.CommandHandler) eh.CommandHandler {
		return eh.CommandHandlerFunc(func(ctx context.Context, cmd eh.Command) error {
			if c, ok := cmd.(Command); ok {
				err := c.Validate()
				if err != nil {
					return err
				}
			}

			// Immediate command execution.
			return h.HandleCommand(ctx, cmd)
		})
	})
}
```


How do you feel about that? Any other idea?

**Comment by apterf** [comment]
And also, we found a problem (maybe a separate issue) when a struct with private fields was used in a command.

https://github.com/looplab/eventhorizon/blob/master/command.go#L155-L167

According to existing logic, private fields will be skipped and the struct will also be treated as zero value.

https://github.com/looplab/eventhorizon/blob/master/commandhandler/aggregate/commandhandler.go#L57-L60

e.g. a custom type from `time.Time`
```go
type customTime time.Time
```



If validator can be added to each different command, can we make it an optional check?
It will be quite difficult to make it generic and always suitable for all cases.

**Comment by maxekman** [comment]
The approach for the validator looks good.

As for the other issue, If you want to open a new issue for that it would also be welcome.

**Comment by apterf** [comment]
Great I will go for this then.
