### ISSUE TITLE
Use EventMatcher when registering event handlers

### ISSUE THREAD

**Issue by maxekman** [looplab/eventhorizon#84]
An example:

```
// EventBus is an interface defining an event bus for distributing events.
type EventBus interface {
	...

	// AddHandler adds a handler for an event.
	AddHandler(EventHandler, EventMatcher)

	...
}
```

```
// EventMatcher is used to match events, used when adding event handlers.
type EventMatcher interface {
	MatchesEvent(EventType) bool
}

// AnyEvent is an EventMatcher that matches any event.
type AnyEvent struct{}

// MatchesEvent imlpements the MatchesEvent method of the EventMatcher interface.
func (m AnyEvent) MatchesEvent(e EventType) bool {
	return true
}

// OneEvent is an EventMatcher that matches a single event.
type OneEvent struct {
	Event EventType
}

// MatchesEvent imlpements the MatchesEvent method of the EventMatcher interface.
func (m OneEvent) MatchesEvent(e EventType) bool {
	return m.Event == e
}

// ManyEvents is an EventMatcher that matches if the event is in the slice.
type ManyEvents []EventType

// MatchesEvent imlpements the MatchesEvent method of the EventMatcher interface.
func (m OneEvent) MatchesEvent(e EventType) bool {
	// return true if e is in the slice.
}
```

**Comment by grrtrr** [comment]
Thank you for sharing this. This idea seemed neat and so I had it copied in one of my projects.

After using it for a while, I ended up _merging both handlers_, 
- it was more straightforward to do the event-filtering at the top of the handler,
- it would return before any shared resources (locks) needed to be taken,
- having to maintain 2 functions per event greatly increased the amount of duplicate code.

Unless there are huge performance considerations (which I doubt, since go makes running many thousands of goroutines at the same time possible), I found it lead to a simpler overall design.

**Comment by maxekman** [comment]
Glad it could help! I would love to hear more about your implementation, maybe you can show an example in a gist?

**Comment by grrtrr** [comment]
This is in magicbus,
- an [event](https://github.com/grrtrr/magicbus/blob/master/event/event.go) is a _directed message_ (`Source() -> Dest()`, it is possible to make `Source()` optional);
- the [`EventHandler`](https://github.com/grrtrr/magicbus/blob/master/event/event.go#L14-L15) both
  + _filters_ events by relevance and
  + _processes_ them, as per above comment.

There are 2 ways to process events:
- for Aggregates, these are multiplexed with Commands (i.e. at most 1 Command or Event is being processed at any time), as per Actor "serialized code" principle;
- everything else (e.g. loggers, writers) can subscribe as [`Observer`](https://github.com/grrtrr/magicbus/blob/master/subscribe.go#L24-L27), which means _immediate notification_.

(Aggregates only get the events whose `Dest()` [matches](https://github.com/grrtrr/magicbus/blob/master/aggregate_actor.go#L60-L67) the AggregateID, and only if they implement the optional [`EventHandler`](https://github.com/grrtrr/magicbus/blob/master/event/event.go#L17-L21) interface).
